name: security-check
op: [push]

jobs:
    security:
    runs-on: ubuntu-latest
    steps:
    -name:checkout code
    uses:actions/checkout@v4

    -name: Dependency vulnerability scan
    run:
    echo "취약점 없음"
    exit 
